### ISSUE TITLE
Not working in Safari 9.1.3

### ISSUE THREAD

**Issue by daslicht** [biesiad/jquery-multidownload#19]
Hi,
 is there a way to make it work with  Safari ?
Cheers Marc

**Comment by biesiad** [comment]
What's the issue?

**Comment by daslicht** [comment]
it's doing nothing

**Comment by biesiad** [comment]
It's hard to say what the problem could be. I just tested locally and it works ok for me in Safari 10.0. Please send me a link to the page where it's not working, and I'll try to diagnose the issue.

I'm starting a local http server with:
```bash
cd test/
python -m SimpleHTTPServer
```
Open `http://localhost:8000/runner.html` in the browser and manually test the links.

**Comment by daslicht** [comment]
You are correct its working, and now I remember what the issue was :)

My client wants to download pdf files , and that was not working , safari just displayed the first file instead of downloading all files.

We have created a server side Zip solution now to get around this odd safari behavior.

I apologize for the turbulence :)

**Comment by daslicht** [comment]
You are correct its working, and now I remember what the issue was :)

My client wants to download pdf files , and that was not working , safari just displayed the first file instead of downloading all files.

We have created a server side Zip solution now to get around this odd safari behavior.

I apologize for the turbulence :)

**Comment by biesiad** [comment]
I suppose server wasn't setting `Content-Disposition` header properly. It's mentioned in the readme.

> Important: All $('.my_links') elements must have defined "href" attribute. "href" must point to documents that generate proper HTML headers ("Content-Disposition: attachment; filename=my_filename").

Play around with it, if you wanna review the workaround.

**Comment by daslicht** [comment]
how do you influence the http header ?
